const cases = [
  {
    id: 'ancilla', index: '01', title: '航益智审', english: 'Ancilla Intelligence', period: '2026',
    role: 'AI 产品经理 / 产品设计 / 全栈交付', status: '企业 Beta v1.3 · 公网可用', tone: 'blue',
    statement: '把 OTA / 航司增值服务配置，转化为可解释、可审计、由人最终决策的审核闭环。',
    image: '/assets/ancilla-desktop.png', imageAlt: '航益智审审核工作台真实界面',
    capabilities: ['AI Native', 'Multi-tenant', 'Remote MCP', 'D1 / Audit', 'Lens Extension'],
    links: [
      { label: '在线体验', href: 'https://hangyi-zhishen.ancilla-guard.workers.dev/' },
      { label: '私有 GitHub（面试展示）', href: 'https://github.com/Ey1111/AncillaGuard' },
      { label: '飞书案例', href: 'https://my.feishu.cn/docx/VYTHdXvwuo5apSx4ODncJxgenJd' },
    ],
    download: { href: '/downloads/ancilla-lens-v0.2.2.zip', version: 'v0.2.2', size: '13 KB' },
    media: [
      { type: 'image', src: '/assets/ancilla-desktop.png', alt: '航益智审桌面审核工作台' },
      { type: 'image', src: '/assets/ancilla-mobile.png', alt: '航益智审移动端界面' },
      { type: 'video', src: '/assets/ancilla-demo.mp4', poster: '/assets/ancilla-desktop.png', alt: '注册、登录、审核与 AI 分析演示' },
      { type: 'video', src: '/assets/ancilla-lens-demo.mp4', poster: '/assets/ancilla-mobile.png', alt: 'Lens 插件安装与使用演示' },
    ],
    caseStudy: {
      background: '机票销售中的行李、退改签、选座等附加权益同时受规则、价格、有效期和渠道页面变化影响。航益智审从单人演示工具推进为企业 Beta：每家企业拥有独立空间、成员角色、规则与审核记录。',
      problem: '审核员要在多个字段和规则间来回比对；负责人只看到结论，却缺少来源、命中规则与人工处置记录。跨企业共用数据还会引入越权风险，外部 Agent 接入后也必须控制可读、可写范围。',
      whyNow: '团队需要的是更快、更可信地做决定，而不是再增加一个聊天框。因此先建立确定性规则和租户隔离底座，再让 AI 负责解释与归纳，最终判断仍交给有权限的人。',
      users: ['审核员：快速发现价格、日期、舱位和权益冲突', '审核主管：查看风险分布、处理效率与规则表现', '企业管理员：管理成员角色、企业规则与数据边界', '规则运营：维护规则版本并追踪误报与漏报'],
      decisions: [
        { title: '规则判定与 AI 解释分层', text: '金额、日期和权益一致性由可复现规则计算；AI 只解释风险和建议下一步，不直接决定通过或驳回。' },
        { title: '企业空间是数据边界', text: '以 organization_id 隔离列表、导入、审核决策、规则与操作审计；管理员、审核员、提交者拥有不同权限。' },
        { title: 'MCP 读写能力分离', text: 'Remote MCP 通过私有 Bearer Token 接入，以读写令牌拆分 6 个工具，并固定在获授权的企业空间内。' },
        { title: '插件按需采集', text: '用户主动扫描后才提取标准化产品字段；离线模式不上传，字段不完整时允许手动修正。' },
        { title: '先闭环，再扩展适配器', text: '先打通提交—规则—解释—人工处置—留痕，再接携程 Sandbox、公开网页适配器与后续正式数据源。' },
      ],
      interactions: [
        { step: '01', title: '采集当前页面', text: '打开机票页后主动启动 Lens，确认来源、字段完整度与连接状态。' },
        { step: '02', title: '规则与 AI 联合审核', text: '确定性规则逐项判断，AI 将命中项整理成审核员可理解的风险说明。' },
        { step: '03', title: '核对证据', text: '原字段、规则结果和 AI 解释并排呈现，先展示证据，再提供建议。' },
        { step: '04', title: '人工处置并留痕', text: '审核员通过或驳回，Web 与 MCP 操作统一写入操作审计；最终决策不可被再次覆盖。' },
      ],
      aiNative: ['确定性规则提供可复现结果', 'AI 解释由规则结果生成，不替代业务签字', '字段缺失、离线和分析失败都有显式降级', '人工处置是最终决策点', 'Remote MCP 让授权 Agent 在同一证据与权限边界内协作'],
      data: ['Cloudflare D1 / SQL 保存企业、成员、提交、规则版本、处置与操作审计', '以 organization_id 作为企业空间隔离边界', '审计记录 Web / MCP 的操作者、对象、结果、备注与时间', '关注平均审核时长、人工改判率、字段缺失率与规则命中率'],
      evidence: ['企业 Beta v1.3 已公网运行，支持企业注册、登录、改密、三类角色与企业空间隔离', '审核队列、搜索筛选、详情、通过 / 驳回、规则中心、AI 审核与数据概览已形成闭环', 'Chrome / Edge Manifest V3 Lens 插件已打包 v0.2.2，可下载并读取携程公开页可见字段', 'Remote MCP 已提供队列、详情、规则、分析、通过与驳回 6 个工具，并实施读写令牌分离', '69 项自动化测试覆盖前端、API、规则、权限与 MCP 链路；Workers + D1 持久化、操作审计及 PC / 移动端适配已验证'],
      boundaries: ['携程能力来自 Sandbox 与公开网页适配器，不是携程官方生产接口；当前也不是携程官方接口。', 'AI 说明基于确定性规则结果生成，线上未接入付费 LLM，不把模板化解释包装成模型推理。', 'Web 已支持企业空间隔离；Remote MCP 仍使用绑定演示企业的私有令牌，尚未升级为 OAuth 2.1。', '当前是可面试演示的企业 Beta，不宣称达到航司生产环境的正式合规、SLA、容灾与业务授权要求。'],
      reflection: '下一轮重点是用人工改判率与字段缺失率持续校准规则和适配器，并将 MCP 的演示企业令牌升级为面向真实组织授权的 OAuth 体系。',
    },
  },
  {
    id: 'origin', index: '02', title: 'Origin Brand AI', english: 'Human-reviewed Brand Brief', period: '2026',
    role: 'AI 产品经理 / 产品设计', status: '真实产品 + 12 页原型', tone: 'paper',
    statement: '让 AI 先提出品牌判断，让人逐字段审核，再形成可信的 Brand Brief。',
    image: '/assets/origin-review.png', imageAlt: 'Origin Brand AI 逐字段审核设计',
    capabilities: ['AI Native', 'PRD', 'Human-in-the-loop', 'Structured Output'],
    links: [
      { label: '可点击原型', href: 'https://modao.cc/ai/share/project/6a883c0c75d0275ef6db5f9c' },
      { label: 'GitHub', href: 'https://github.com/Ey1111/origin-brand-ai' },
      { label: 'PRD V1.0', href: 'https://my.feishu.cn/docx/PlpkdciBIoqyxXxiTnvc3ERanx7' },
    ],
    media: [{ type: 'image', src: '/assets/origin-review.png', alt: '逐字段审核页面' }],
    caseStudy: {
      background: '品牌需求往往从零散自然语言开始，目标用户、市场、价格与调性互相影响。直接让模型生成完整方案，会把未经确认的假设写进最终 Brief。',
      problem: '用户不知道 AI 改了哪些字段，也难以逐项保留、编辑或拒绝；一键生成把“模型建议”和“业务事实”混在一起，容易造成下游返工。',
      whyNow: 'AI 能快速扩展思路，但品牌判断需要责任归属。产品价值是降低澄清成本，并保留每一次人工取舍。',
      users: ['独立品牌负责人：把模糊想法整理成可执行 Brief', '品牌 / 产品经理：逐项确认定位、范围与约束', '设计与内容团队：接收结构一致、来源清楚的上游输入'],
      decisions: [
        { title: '逐字段审核', text: '每条建议均可接受、编辑后接受或拒绝，处理状态与进度持续可见。' },
        { title: 'AI 建议不自动写入', text: '模型输出先进入审核层，只有人的确认才进入 Brand Brief。' },
        { title: '结构化输出约束模型', text: '固定字段与 Schema 校验让前端稳定比较当前值和建议值，并显式处理失败。' },
      ],
      interactions: [
        { step: '01', title: '创建品牌项目', text: '输入原始想法与已知约束，保留原话作为事实底稿。' },
        { step: '02', title: 'AI 需求分析', text: '拆出目标用户、市场、价格、场景和调性等建议字段。' },
        { step: '03', title: '逐字段审核', text: '用户比较当前值与 AI 建议，接受、编辑后接受或拒绝。' },
        { step: '04', title: '确认版本并导出', text: '仅将确认字段组合成 Brief，支持 V1 → 修订草稿 → V2 与 Markdown 导出。' },
      ],
      aiNative: ['模型负责扩展与结构化，不负责最终写入', '字段级人机协作让错误可定位、可回退', 'Prompt、Token、成本、延迟与错误进入审计', '超时、解析失败和冲突均有产品状态'],
      data: ['Supabase / PostgreSQL 持久化项目、版本和审核状态', 'RLS 保证用户只能访问自己的项目', '建议质量可按接受、编辑、拒绝与重生成行为评估'],
      evidence: ['邮箱 OTP、项目 CRUD、真实模型调用和不可变 V1 已实现', '18 页 PRD 与 12 页墨刀原型覆盖主链路、逆向链路和异常状态', '逐字段审核、V2 与导出已定义，按实现 / 原型 / 规划明确标注'],
      boundaries: ['逐字段审核、V2 和 Markdown 导出部分仍处于原型 / 收口阶段。', '不宣称已形成生产级模型评测体系或团队协作能力。'],
      reflection: '生成质量不只看文字是否顺畅，更要观察用户改了什么、为什么改，以及是否减少下游返工。',
    },
  },
  {
    id: 'rivaltrace', index: '03', title: 'RivalTrace AI', english: 'Competitive Intelligence Workspace', period: '2026',
    role: 'AI 产品经理 / 数据产品设计', status: '本地 MVP · 可审阅', tone: 'signal',
    statement: '把竞品网页变化变成有来源、有差异、有优先级的情报。',
    image: '/assets/rivaltrace-workspace.png', imageAlt: 'RivalTrace AI 实时情报流界面',
    capabilities: ['AI Native', 'SQL / SQLite', 'Competitive Intelligence', 'Evidence'],
    links: [{ label: '飞书案例', href: 'https://my.feishu.cn/docx/VYTHdXvwuo5apSx4ODncJxgenJd#doxcnlFZpcsfxx1xS5ewM9N9Xhd' }],
    media: [{ type: 'image', src: '/assets/rivaltrace-workspace.png', alt: '实时情报流与证据详情' }],
    caseStudy: {
      background: '竞品更新分散在官网、定价页和博客。手动巡检成本高，截图和群消息也难形成长期记忆。',
      problem: '抓到页面不等于产生情报：需要去重、保留前后版本、定位变化、判断影响，并让分析者回到证据源。',
      whyNow: '模型适合归纳变化与影响，但没有版本和来源约束就会产生不可追溯的结论。因此先建设证据链，再接 AI。',
      users: ['产品经理：判断竞品功能与定位变化', '市场 / 战略：识别定价、套餐与叙事信号', '研究人员：回看原始来源与历史版本'],
      decisions: [
        { title: '去重先于 AI 分析', text: '清洗正文并计算内容指纹，无变化时不新建情报，降低噪声和模型成本。' },
        { title: '差异与原始来源共同展示', text: '保存前后版本和 line diff，AI 结论必须回到来源。' },
        { title: '优先级只辅助排序', text: '主题、影响、置信度和优先级为结构化建议，保留人工审核状态。' },
      ],
      interactions: [
        { step: '01', title: '添加监控来源', text: '指定官网、定价页或博客，形成竞品监控列表。' },
        { step: '02', title: '抓取与版本去重', text: '清洗正文、写入 SQLite 基线；内容不变则停止。' },
        { step: '03', title: '生成差异与分析', text: '计算 line diff，DeepSeek 输出结构化主题、影响与优先级。' },
        { step: '04', title: '审核进入情报流', text: '按竞品、时间与状态浏览，打开详情核对来源和原始差异。' },
      ],
      aiNative: ['LLM 消化受约束的差异，不对整页自由发挥', '每条结论绑定来源与版本', '抓取失败、内容不变和模型失败分别建模', '人工审核决定是否进入正式决策'],
      data: ['SQLite 保存 competitor、source、snapshot、diff 与 insight', '内容哈希负责版本去重，时间与来源支持审计', '关注有效变化率、重复率、情报审核通过率和信号到决策时长'],
      evidence: ['添加竞品—抓取—清洗—SQLite 基线—版本去重已跑通', 'line diff、DeepSeek 结构化分析与持久化详情已形成闭环'],
      boundaries: ['当前以本地工作台为主，调度、反爬和多租户仍需工程化。', '优先级评分是辅助判断，不等同于真实商业影响。'],
      reflection: '情报产品的价值不是抓得多，而是持续减少噪声，并把变化连接到可解释的产品判断。',
    },
  },
  {
    id: 'sentinel', index: '04', title: 'Sentinel', english: 'Evidence-bound Release QA Agent', period: '2026',
    role: 'AI 产品经理 / Agent 工作流设计', status: '在研 · 证据层已验证', tone: 'violet',
    statement: '让发布验收从一句目标，变成可执行、可观察、可追责的证据链。',
    image: '/assets/sentinel-dashboard.png', imageAlt: 'Sentinel Release QA 产品界面',
    capabilities: ['Agent Workflow', 'Playwright', 'Evidence', 'Release QA'],
    links: [{ label: 'GitHub', href: 'https://github.com/Ey1111/sentinel-ai-release-qa-agent' }, { label: '飞书案例', href: 'https://my.feishu.cn/docx/VYTHdXvwuo5apSx4ODncJxgenJd' }],
    media: [{ type: 'image', src: '/assets/sentinel-dashboard.png', alt: 'Sentinel 运行证据面板' }],
    caseStudy: {
      background: '版本上线前的验收常以自然语言目标开始。若 Agent 只返回“通过 / 失败”，团队无法判断它执行了什么、看到了什么，也无法复现问题。',
      problem: '目标要拆成可执行步骤；浏览器运行需要受控；观察结果必须绑定证据；模型推断不能覆盖真实执行结果。',
      whyNow: 'Agent 越能跨页面执行，越需要证据、权限和失败边界。Sentinel 从“可信验收”而非“自动点击”定义产品。',
      users: ['产品经理：用业务语言提交验收目标', 'QA：核对步骤、证据和问题详情', '研发 / 发布负责人：定位失败发生在哪一步'],
      decisions: [
        { title: 'Planner、QA、Observer 分责', text: '拆解、执行与观察相互独立，避免同一 Agent 自证成功。' },
        { title: '确定性执行优先', text: '真实浏览器动作和状态是事实层，模型不能描述未执行步骤。' },
        { title: 'Bug 必须绑定证据', text: '问题详情包含步骤、预期、实际与截图 / 日志引用；当前保持只读。' },
      ],
      interactions: [
        { step: '01', title: '定义发布目标', text: '输入授权测试地址、业务旅程和成功结果。' },
        { step: '02', title: '审核测试计划', text: 'Planner 将目标拆成步骤，用户执行前确认范围。' },
        { step: '03', title: '浏览器执行与观察', text: 'QA 驱动 Playwright，Observer 采集页面状态与证据。' },
        { step: '04', title: '复核结果与 Bug', text: '按 PASS / FAIL、步骤与证据查看运行，问题保持可追溯。' },
      ],
      aiNative: ['角色分工减少自我确认偏差', '模型判断被限定在真实执行证据内', '失败步骤不会被自然语言总结掩盖', '自动化前保留目标与计划确认'],
      data: ['run、step、observation、artifact 与 bug report 构成证据模型', '状态机区分 draft、running、pass、fail 与 blocked', '关注可复现 Bug 比例、人工复核耗时、误报率与运行成功率'],
      evidence: ['Planner、QA、Observer / Critic 与确定性执行结构已建立', '基于官方 TypeScript MCP SDK 实现 stdio MCP Server，提供计划生成、审批、执行与 Bug Draft 等 6 个高层工具', '真实 Chromium 覆盖隔离、跨域拦截、网络失败、敏感信息保护、证据关联与 MCP 子进程握手，当前 20 项集成测试通过', '当前 Bug 详情保持只读，未夸大为自动提单'],
      boundaries: ['当前不宣称已自动创建 GitHub Issue。', '目标网站必须是用户有权测试的环境。'],
      reflection: 'Agent 的可信度来自它愿意展示“不知道、没执行、证据不足”，而不是永远给出完整答案。',
    },
  },
  {
    id: 'nextmind', index: '05', title: 'NextMind Slides', english: 'AI Presentation System', period: '2026.06—至今',
    role: 'AI 产品（视觉设计方向）实习生', status: '实习项目 · 持续迭代', tone: 'rose',
    statement: '把 20+ 项 AI 演示功能整理为可理解、可验收、可商业化表达的产品体系。',
    image: '/assets/nextmind-poster.webp', imageAlt: 'NextMind Slides 品牌宣传主视觉',
    capabilities: ['AI Product Storytelling', 'Product Docs', 'Prompt Iteration', 'AIGC'],
    links: [{ label: '网站案例', href: 'https://ciyanglamu.top/' }],
    media: [
      { type: 'image', src: '/assets/nextmind-poster.webp', alt: 'NextMind 宣传主视觉' },
      { type: 'image', src: '/assets/nextmind-map.webp', alt: 'AI 产品思维导图' },
      { type: 'image', src: '/assets/nextmind-payment.webp', alt: '产品支付界面' },
      { type: 'video', src: '/assets/nextmind.mp4', poster: '/assets/nextmind-poster.webp', alt: 'NextMind 宣传片节选' },
    ],
    caseStudy: {
      background: 'NextMind 围绕思路生成、结构表达、幻灯优化、内容可视化与沟通表达提供完整演示生命周期能力。我的工作连接产品能力梳理、生成效果验收与商业化表达。',
      problem: '20+ 项功能和 18 类场景分散在不同材料中；若只罗列功能，团队难以形成统一产品语言，用户也无法理解不同场景、套餐与价值之间的关系。',
      whyNow: '产品能力快速扩展并进入商业化表达阶段，需要稳定的信息架构、场景模板和 AI 验收清单支撑迭代与官网上线。',
      users: ['内部产品与业务团队：理解功能边界、场景与版本差异', '投标、融资路演、高管汇报、市场研究与产品发布用户', '需要选择 Free、Plus、Pro 或 Enterprise 方案的潜在用户'],
      decisions: [
        { title: '功能归纳为能力体系', text: '把提示增强、需求澄清、Text2Deck、智能提纲、Context2Image 与模板融合等 20+ 项功能归纳为五类产品能力。' },
        { title: '场景沉淀为母模板', text: '把 18 类演示场景归纳为说服、决策、汇报、分析、传播五类母模板，明确用户、任务、内容顺序与标准页面。' },
        { title: '生成效果必须可验收', text: '从信息准确性、结构完整性、表达一致性和场景匹配度记录问题，以 Prompt、版本与失败案例台账推动迭代。' },
        { title: '能力表达连接商业化', text: '按 Free、Plus、Pro、Enterprise 四档方案说明场景、价值主张与版本差异，而不是堆叠功能名。' },
      ],
      interactions: [
        { step: '01', title: '梳理功能体系', text: '把 20+ 项功能映射到五类能力，推动《产品功能》迭代至 V2.5。' },
        { step: '02', title: '建立场景模板', text: '梳理 18 类演示场景，定义目标用户、核心任务、内容顺序与标准页面结构。' },
        { step: '03', title: '走查 AI 结果', text: '按四个验收维度记录问题，以 6 版方案与 4 轮迭代沉淀生成结果验收清单。' },
        { step: '04', title: '支持商业化表达', text: '参与四档产品方案与官网定价页梳理，说明使用场景、核心价值和版本差异。' },
      ],
      aiNative: ['Prompt 与版本作为可追踪的生成参数', '准确性、完整性、一致性和场景匹配度构成验收维度', '失败案例进入台账，人工走查决定结果是否可用', 'AI 生成服务于明确场景与内容结构，而不是替代产品判断'],
      data: ['20+ 项功能归纳为 5 类产品能力', '18 类场景沉淀为 5 类母模板', 'Prompt 与失败案例台账跟踪 6 版方案和 4 轮迭代', '商业化表达覆盖 Free、Plus、Pro、Enterprise 四档方案'],
      evidence: ['《产品功能》已迭代至 V2.5，包含能力体系、功能说明与信息架构', '形成场景表、标准页面结构与 AI 生成结果验收清单', '参与官网定价页和四档产品方案内容梳理', '实习期间 20 天推动宣传片从需求、15 个方案版本、8 轮评审到上线'],
      boundaries: ['仅描述本人实际参与的产品表达、分镜、生成、实拍和发布物料，不扩大为整个产品所有权。'],
      reflection: '复杂 AI 产品表达要先建立信息架构，再针对内部决策和外部传播选择不同叙事密度。',
    },
  },
  {
    id: 'snow', index: '06', title: '雪域“纯”香', english: 'Highland Barley Chocolate', period: '2024—2025',
    role: '项目负责人 / 5 人跨专业团队', status: '省级优秀 · 实物验证', tone: 'cocoa',
    statement: '把青稞研究推进为真实产品、品牌、试销和反馈闭环。',
    image: '/assets/chocolate-product.webp', imageAlt: '雪域纯香青稞巧克力产品实拍',
    capabilities: ['0→1 Product', 'User Research', 'Brand', 'Team Leadership'],
    links: [{ label: '飞书案例', href: 'https://my.feishu.cn/docx/N6Z9d9s69o3wYMx2MiVchLYmnKd' }, { label: '网站案例', href: 'https://ciyanglamu.top/' }],
    media: [
      { type: 'image', src: '/assets/chocolate-product.webp', alt: '雪域纯香实体产品' },
      { type: 'image', src: '/assets/chocolate-poster.webp', alt: '雪域纯香传播海报' },
      { type: 'image', src: '/assets/chocolate-award.webp', alt: '省级优秀结项证据' },
      { type: 'video', src: '/assets/chocolate.mp4', poster: '/assets/chocolate-product.webp', alt: '雪域纯香 AI 宣传视频' },
    ],
    caseStudy: {
      background: '项目以西藏青稞为特色原料，连接功能性研究、食品产品与数字传播。目标不是只交比赛材料，而是做出能试吃、能反馈的真实产品。',
      problem: '五人团队横跨食品、计算机与数字媒体，研究、配方、包装、官网和运营容易各自完成，却无法形成共同用户价值。',
      whyNow: '青稞研究需要一个面向消费者的验证载体；实体巧克力能把抽象功能性转化为口味、包装与购买反馈。',
      users: ['关注健康和地方特色的年轻消费者', '需要验证青稞产品市场表达的项目团队'],
      decisions: [
        { title: '从大平台收敛到产品 MVP', text: '优先验证口味、包装、付费意愿与品牌表达，不把区块链设想当成已实现能力。' },
        { title: '真实样品替代概念展示', text: '把研究推进到可试吃、可拍摄、可售卖的产品。' },
        { title: '反馈进入下一轮', text: '21 人偏好测试、内测和小范围试销用于调整 SKU 与包装，而不是只作为附件。' },
      ],
      interactions: [
        { step: '01', title: '研究与定位', text: '从青稞 β-葡聚糖与低脂方向定义产品价值，同时标明研究边界。' },
        { step: '02', title: '试制与品牌', text: '完成样品、包装 1.0—2.0、视觉和数字展示。' },
        { step: '03', title: '用户测试', text: '通过 21 人偏好测试与内部测评收敛口味和首发 SKU。' },
        { step: '04', title: '小范围试销', text: '用真实购买和询价反馈检验表达与产品体验。' },
      ],
      aiNative: ['该项目不是 AI 产品；在作品集中用于证明从研究到市场验证的通用产品能力'],
      data: ['21 人偏好测试', '内测、问卷和 5 份买家反馈记录', '以小样本结果支持包装与表达迭代，不外推大市场'],
      evidence: ['带领 5 人团队推进 13 个月', '省级创新创业训练计划优秀结项', '完成实体产品、官网、宣传与小范围付费验证', '研究论文、项目书、商标和外观专利材料可查'],
      boundaries: ['样本规模较小，结果只用于方向验证。', '健康、低脂与产业影响不表述为未经第三方验证的确定结论。'],
      reflection: '真正的 0→1 不是做齐物料，而是让跨专业交付围绕同一用户价值闭环。',
    },
  },
]

export const projects = cases

export const portfolioLinks = [
  { label: '飞书作品集', note: '简历、案例、PRD 与演示视频的持续更新主页', href: 'https://my.feishu.cn/docx/VYTHdXvwuo5apSx4ODncJxgenJd' },
  { label: 'Origin PRD', note: '18 页 V1.0：目标、流程、状态、AI 边界与验收', href: 'https://my.feishu.cn/docx/PlpkdciBIoqyxXxiTnvc3ERanx7' },
  { label: 'Origin 墨刀原型', note: '12 页完整项目，可点击体验主链路与异常流程', href: 'https://modao.cc/ai/share/project/6a883c0c75d0275ef6db5f9c' },
  { label: 'GitHub', note: 'Origin 与 Sentinel 的工程、测试和迭代记录', href: 'https://github.com/Ey1111' },
]

export const hobbies = [
  { category: '板绘', note: '角色、氛围与叙事构图', image: '/materials/hobbies/media/04.webp' },
  { category: '烘焙', note: '配方、手感与耐心', image: '/materials/hobbies/media/08.webp' },
  { category: '运动', note: '骑行与户外探索', image: '/materials/hobbies/media/13.webp' },
]
